# Generated by Django 3.0.2 on 2020-02-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
